// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package port

import (
	"context"
	"modular-monolith-libraryApp/modules/user/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// FindByCPF provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByCPF(ctx context.Context, cpf string) (domain.User, error) {
	ret := _mock.Called(ctx, cpf)

	if len(ret) == 0 {
		panic("no return value specified for FindByCPF")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, cpf)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, cpf)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cpf)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByCPF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCPF'
type MockUserRepository_FindByCPF_Call struct {
	*mock.Call
}

// FindByCPF is a helper method to define mock.On call
//   - ctx context.Context
//   - cpf string
func (_e *MockUserRepository_Expecter) FindByCPF(ctx interface{}, cpf interface{}) *MockUserRepository_FindByCPF_Call {
	return &MockUserRepository_FindByCPF_Call{Call: _e.mock.On("FindByCPF", ctx, cpf)}
}

func (_c *MockUserRepository_FindByCPF_Call) Run(run func(ctx context.Context, cpf string)) *MockUserRepository_FindByCPF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByCPF_Call) Return(user domain.User, err error) *MockUserRepository_FindByCPF_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByCPF_Call) RunAndReturn(run func(ctx context.Context, cpf string) (domain.User, error)) *MockUserRepository_FindByCPF_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Save(ctx context.Context, user domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserRepository_Expecter) Save(ctx interface{}, user interface{}) *MockUserRepository_Save_Call {
	return &MockUserRepository_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *MockUserRepository_Save_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Save_Call) Return(err error) *MockUserRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Save_Call) RunAndReturn(run func(ctx context.Context, user domain.User) error) *MockUserRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
