// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package port

import (
	"context"
	"modular-monolith-libraryApp/modules/author/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorRepository creates a new instance of MockAuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorRepository {
	mock := &MockAuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorRepository is an autogenerated mock type for the AuthorRepository type
type MockAuthorRepository struct {
	mock.Mock
}

type MockAuthorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorRepository) EXPECT() *MockAuthorRepository_Expecter {
	return &MockAuthorRepository_Expecter{mock: &_m.Mock}
}

// ExistsAll provides a mock function for the type MockAuthorRepository
func (_mock *MockAuthorRepository) ExistsAll(ctx context.Context, ids []string) (bool, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ExistsAll")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (bool, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) bool); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthorRepository_ExistsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsAll'
type MockAuthorRepository_ExistsAll_Call struct {
	*mock.Call
}

// ExistsAll is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockAuthorRepository_Expecter) ExistsAll(ctx interface{}, ids interface{}) *MockAuthorRepository_ExistsAll_Call {
	return &MockAuthorRepository_ExistsAll_Call{Call: _e.mock.On("ExistsAll", ctx, ids)}
}

func (_c *MockAuthorRepository_ExistsAll_Call) Run(run func(ctx context.Context, ids []string)) *MockAuthorRepository_ExistsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorRepository_ExistsAll_Call) Return(b bool, err error) *MockAuthorRepository_ExistsAll_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuthorRepository_ExistsAll_Call) RunAndReturn(run func(ctx context.Context, ids []string) (bool, error)) *MockAuthorRepository_ExistsAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockAuthorRepository
func (_mock *MockAuthorRepository) FindByID(ctx context.Context, id string) (domain.Author, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Author, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Author); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Author)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthorRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAuthorRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthorRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockAuthorRepository_FindByID_Call {
	return &MockAuthorRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAuthorRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockAuthorRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorRepository_FindByID_Call) Return(author domain.Author, err error) *MockAuthorRepository_FindByID_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockAuthorRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Author, error)) *MockAuthorRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAuthorRepository
func (_mock *MockAuthorRepository) Save(ctx context.Context, author domain.Author) error {
	ret := _mock.Called(ctx, author)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Author) error); ok {
		r0 = returnFunc(ctx, author)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthorRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAuthorRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - author domain.Author
func (_e *MockAuthorRepository_Expecter) Save(ctx interface{}, author interface{}) *MockAuthorRepository_Save_Call {
	return &MockAuthorRepository_Save_Call{Call: _e.mock.On("Save", ctx, author)}
}

func (_c *MockAuthorRepository_Save_Call) Run(run func(ctx context.Context, author domain.Author)) *MockAuthorRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Author
		if args[1] != nil {
			arg1 = args[1].(domain.Author)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorRepository_Save_Call) Return(err error) *MockAuthorRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthorRepository_Save_Call) RunAndReturn(run func(ctx context.Context, author domain.Author) error) *MockAuthorRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
